/******************************************************************************/
/***        Generated by IBExpert 2015.12.21.1 24/10/2018 17:28:07        ***/
/******************************************************************************/

/******************************************************************************/
/***     Following SET SQL DIALECT is just for the Database Comparer      ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                              Generators                              ***/
/******************************************************************************/

CREATE GENERATOR CR_ARQUIVOS;
SET GENERATOR CR_ARQUIVOS TO 52;



/******************************************************************************/
/***                                Tables                                ***/
/******************************************************************************/



CREATE TABLE ARQUIVOS (
    CODIGO   INTEGER NOT NULL,
    ARQUIVO  BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

CREATE TABLE CONFIGURACOES (
    CONFIG  VARCHAR(50) NOT NULL,
    VALOR   VARCHAR(5000)
);



/******************************************************************************/
/***                             Primary keys                             ***/
/******************************************************************************/

ALTER TABLE ARQUIVOS ADD CONSTRAINT PK_ARQUIVOS PRIMARY KEY (CODIGO);
ALTER TABLE CONFIGURACOES ADD CONSTRAINT PK_CONFIGURACOES PRIMARY KEY (CONFIG);