select	N.CODVENDA
		, N.NF_DT_EMISSAO
		, N.CODVENDA
		, N.NF_NATUREZA_OPERACAO
		, V.RAZAOSOCIAL
		, V.NOTAFISCAL
		, V.TOTAL
		, N.NF_NUMERO
		, N.NF_CHAVE
		, N.NF_SITUACAO
from	NOTA_FISCAL N
left join VENDA V on N.CODVENDA = V.CODIGO
left join VENDA_PRODUTO VP on VP.CODVENDA = V.CODIGO
left join VENDA_TIPO VT on VT.DESCRICAO = V.VENDA_TIPO
where	(N.NF_SITUACAO = 'Autorizada' or N.NF_SITUACAO = 'confirmada')
and		N.CODEMPRESA = 1
and		N.NF_NUMERO between :NFI and :NFF
and		N.NF_DT_EMISSAO between :I and :F
and		N.NF_AMBIENTE = 1
and		(VP.CODNF_CFOP = '5102' or VP.CODNF_CFOP = '6102' or VP.CODNF_CFOP = '5949')
group by N.CODVENDA
		 , N.NF_DT_EMISSAO
		 , N.CODVENDA
		 , N.NF_NATUREZA_OPERACAO
		 , V.RAZAOSOCIAL
		 , V.NOTAFISCAL
		 , V.TOTAL
		 , N.NF_NUMERO
		 , N.NF_CHAVE
		 , N.NF_SITUACAO